### ISSUE TITLE
Error checking SMTP credentials.

### ISSUE THREAD

**Issue by judge2020** [complemento/docker.otrs#2]
Sorry if this should be instead directed towards the main OTRS repo, but I doubt it's broken there (can't check). 

Running the docker and going through the setup process, when I come to the mail configuration page and enter my details. When trying to run the test configuration, I get an error in the apache error.log:

```
[Mon Jan 22 02:14:50.216686 2018] [:error] [pid 24] Can't call method "ObjectLogStart" on an undefined value at /opt/otrs/Kernel/System/Email/SMTP.pm line 48.
```

**Comment by richieri** [comment]
Hi! I'll check it. I'm opening an internal ticket for checking with my team. Thanks!

**Comment by richieri** [comment]
Hi!

It seems to be an error with OTRS installer. We tried in a fresh new installation, on a Debian virtual server (not docker), and same error occurred.

I suggest that you skip this step and make the configuration after the installation has finished, using the Admin menu at Agent Interface.

You can also try to install on other linux distro  and see if the error is the same, since, this docker image is also Debian based.

Regards!

**Comment by anick012** [comment]
Hi!
I confirm, problem is still here. 
Fresh install Centos 7, otrs-6.0.6-01.noarch.rpm

BR

**Comment by richieri** [comment]
Dear @anick012, I suggest you to also register a bug on OTRS bugzilla, since it's an error in their installer, not in our Docker image.
